# remap prefix
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# Split panes
bind h split-window -h
bind v split-window -v
unbind '"'
unbind %

# Scroll
set -g mouse on

# Easy config reloads
bind r source-file ~/.tmux.conf

# Stop auto rename windows
set-option -g allow-rename off

# Increase history
set -g history-limit 500000

# Lower escape timing for quicker response to scroll-buffer access
set -s escape-time 50

# Design tweaks
set -g visual-activity on
set -g visual-bell off
set -g visual-silence off
set -g bell-action none
set -g status-bg blue
set -g status-fg black
